services:
    app:
        build:
            context: .
        links:
            - database
        environment:
            NODE_ENV: production

    database:
        image: mysql:8
        volumes:
            - database:/data/db
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - 127.0.0.1:3306:3306

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 127.0.0.1:${PHPMYADMIN_PORT}:80
        environment:
            - PMA_ARBITRARY=1

volumes:
    database:
